#!/bin/sh

user_vm="${HOME}/.gentoo/java-config-2/current-user-vm"
system_vm="/etc/java-config-2/current-system-vm"

# Try GENTOO_VM
if [[ -n ${GENTOO_VM} ]]; then
	vmpath="/usr/lib/jvm/${GENTOO_VM}/"
# Then user VM
elif [[ -h ${user_vm} ]]; then
	vmpath=$(readlink ${user_vm})
# And fall back to the system VM
else
	vmpath=$(readlink ${system_vm})
fi
javacmd=${vmpath}/bin/java

# Switch to the directory of the script.
cd "$(dirname "${BASH_SOURCE[0]}")"

for file in lib/*.jar; do
	CLASSPATH+="${CLASSPATH:+:}$file"
done

exec ${javacmd} ${JAVA_OPTIONS} -classpath ${CLASSPATH} org.artifactory.cli.main.ArtAdmin "$@"
