#!/sbin/runscript
# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

description="Open platform to manage code quality"

wrapper_conf=/etc/__SLOTNAME__/wrapper.conf
log_dir=/var/log/__SLOTNAME__
temp_dir=/var/tmp/__SLOTNAME__
user=${SONAR_USER:-"sonar"}
group=${SONAR_GROUP:-"sonar"}
shutdown_wait=${SHUTDOWN_WAIT:-"30"}

pidfile=${PIDFILE:-/run/__SLOTNAME__/sonar.pid}
command="__BASE_DIR__/bin/wrapper"
command_args="${wrapper_conf} wrapper.pidfile=${pidfile} wrapper.daemonize=TRUE"

depend() {
	need net
	use postgres
}

start_pre() {
	checkpath -d -o "${user}:${group}" -m750 "${log_dir}"
	checkpath -d -o "${user}:${group}" -m700 "${temp_dir}"
	checkpath -d -o "${user}:${group}" -m700 `dirname ${pidfile}`
}

start() {
	ebegin "Starting Sonar __SONAR_VER__"

	start-stop-daemon --start \
		--user=${user} --group=${group} \
		--pidfile="${pidfile}" \
		--exec ${command} -- ${command_args}
	eend $?
}

stop() {
	ebegin "Stopping Sonar __SONAR_VER__"

	start-stop-daemon --stop \
		--pidfile="${pidfile}" \
		--retry=TERM/${shutdown_wait}/KILL/10 \
		--exec ${command} -- ${command_args}
	eend $?
}
